# Generated by Django 3.2.4 on 2021-09-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=12)),
                ('task_duration', models.TimeField()),
                ('day', models.CharField(max_length=12)),
                ('task_status', models.CharField(max_length=12)),
            ],
        ),
    ]
